# Generated by Django 5.2.10 on 2026-02-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/cart/', verbose_name='Изображение для корзины'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Теги через запятую (Хит, Новинка, Ограниченный)', max_length=200, verbose_name='Теги'),
        ),
    ]
