# Generated by Django 5.2.10 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_cart_image_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chat ID для уведомлений'),
        ),
    ]
