# Generated by Django 5.2.10 on 2026-03-01 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_fix_telegramuser_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Меньшее число = выше на странице', verbose_name='Порядок отображения'),
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('language_code', models.CharField(blank=True, max_length=10, verbose_name='Язык')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Chat ID для уведомлений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последний раз')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['telegram_id'], name='store_teleg_telegra_c8b898_idx'), models.Index(fields=['username'], name='store_teleg_usernam_ebc8aa_idx'), models.Index(fields=['last_seen'], name='store_teleg_last_se_40054b_idx')],
            },
        ),
    ]
