# Generated by Django 5.2.10 on 2026-02-26 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_product_cart_image_alter_product_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_month', models.DateField(unique=True)),
                ('customer_count', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('retention_rates', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-cohort_month'],
            },
        ),
        migrations.CreateModel(
            name='AggregatedStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('granularity', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('stat_type', models.CharField(choices=[('revenue', 'Revenue'), ('orders', 'Orders'), ('sessions', 'Sessions'), ('visitors', 'Visitors'), ('conversion_rate', 'Conversion Rate'), ('aov', 'Average Order Value'), ('cart_abandonment', 'Cart Abandonment Rate'), ('checkout_abandonment', 'Checkout Abandonment Rate'), ('revenue_per_visitor', 'Revenue per Visitor'), ('ltv', 'Lifetime Value'), ('retention', 'Retention Rate'), ('churn', 'Churn Rate'), ('romi', 'ROMI'), ('product_margin', 'Product Margin')], db_index=True, max_length=50)),
                ('dimensions', models.JSONField(blank=True, db_index=True, default=dict)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('value_prev', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('count', models.IntegerField(default=0)),
                ('dimensions_hash', models.CharField(blank=True, db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'stat_type'], name='analytics_a_date_676155_idx'), models.Index(fields=['stat_type', 'date'], name='analytics_a_stat_ty_be478e_idx')],
                'unique_together': {('date', 'granularity', 'stat_type', 'dimensions_hash')},
            },
        ),
        migrations.CreateModel(
            name='ChannelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('sessions', models.IntegerField(default=0)),
                ('visitors', models.IntegerField(default=0)),
                ('orders', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('romi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cpa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-revenue'],
                'indexes': [models.Index(fields=['channel', '-date'], name='analytics_c_channel_147f71_idx')],
                'unique_together': {('channel', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('utm_term', models.CharField(blank=True, max_length=200)),
                ('utm_content', models.CharField(blank=True, max_length=200)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('landing_page', models.URLField(blank=True, max_length=500)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(default='unknown', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('scroll_depth', 'Scroll Depth'), ('click', 'Click'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('checkout_start', 'Checkout Start'), ('checkout_step', 'Checkout Step'), ('purchase', 'Purchase'), ('web_vital', 'Web Vital'), ('custom', 'Custom')], db_index=True, max_length=50)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.trackingsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FunnelStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(choices=[(1, 'Главная / Landing'), (2, 'Каталог'), (3, 'Карточка товара'), (4, 'Корзина'), (5, 'Начало оформления'), (6, 'Доставка'), (7, 'Оплата'), (8, 'Заказ создан'), (9, 'Оплата подтверждена')])),
                ('reached_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_steps', to='analytics.trackingsession')),
            ],
            options={
                'ordering': ['session', 'step'],
            },
        ),
        migrations.CreateModel(
            name='ProductMarginStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cogs', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('abc_category', models.CharField(default='C', max_length=1)),
                ('xyz_category', models.CharField(default='Z', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margin_stats', to='store.product')),
            ],
            options={
                'ordering': ['-margin'],
                'indexes': [models.Index(fields=['date', '-margin'], name='analytics_p_date_ea3473_idx'), models.Index(fields=['abc_category'], name='analytics_p_abc_cat_3ff2e6_idx'), models.Index(fields=['xyz_category'], name='analytics_p_xyz_cat_c95424_idx')],
                'unique_together': {('product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RFMSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('monetary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('r_score', models.IntegerField(default=1)),
                ('f_score', models.IntegerField(default=1)),
                ('m_score', models.IntegerField(default=1)),
                ('rfm_score', models.IntegerField(default=1)),
                ('segment', models.CharField(db_index=True, max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('cohort_month', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfm_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rfm_score'],
                'indexes': [models.Index(fields=['segment'], name='analytics_r_segment_ccde54_idx'), models.Index(fields=['user', '-calculated_at'], name='analytics_r_user_id_9f8edc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['session_key'], name='analytics_t_session_c9ad2a_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['user', '-started_at'], name='analytics_t_user_id_b63f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['utm_source', '-started_at'], name='analytics_t_utm_sou_66771d_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingsession',
            index=models.Index(fields=['is_active', '-last_activity'], name='analytics_t_is_acti_ac8432_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['session', '-created_at'], name='analytics_t_session_322ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['user', '-created_at'], name='analytics_t_user_id_bd7774_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['event_type', '-created_at'], name='analytics_t_event_t_7ceebd_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['event_name', '-created_at'], name='analytics_t_event_n_921e48_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['created_at'], name='analytics_t_created_81a052_idx'),
        ),
        migrations.AddIndex(
            model_name='funnelstep',
            index=models.Index(fields=['step', '-reached_at'], name='analytics_f_step_95ce6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='funnelstep',
            unique_together={('session', 'step')},
        ),
    ]
