# Generated by Django 5.2.10 on 2026-02-26 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregatedstat',
            options={'verbose_name': 'Агрегированная статистика', 'verbose_name_plural': 'Агрегированные статистики'},
        ),
        migrations.AlterModelOptions(
            name='trackingevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='trackingsession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Сессия', 'verbose_name_plural': 'Сессии'},
        ),
        migrations.AlterField(
            model_name='aggregatedstat',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='aggregatedstat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='aggregatedstat',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='aggregatedstat',
            name='dimensions',
            field=models.JSONField(blank=True, db_index=True, default=dict, verbose_name='Измерения'),
        ),
        migrations.AlterField(
            model_name='aggregatedstat',
            name='dimensions_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Хеш измерений'),
        ),
        migrations.AlterField(
            model_name='aggregatedstat',
            name='granularity',
            field=models.CharField(choices=[('hourly', 'Почасово'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='daily', max_length=20, verbose_name='Гранулярность'),
        ),
        migrations.AlterField(
            model_name='aggregatedstat',
            name='stat_type',
            field=models.CharField(choices=[('revenue', 'Выручка'), ('orders', 'Заказы'), ('sessions', 'Сессии'), ('visitors', 'Посетители'), ('conversion_rate', 'Конверсия'), ('aov', 'Средний чек'), ('cart_abandonment', 'Брошенные корзины'), ('checkout_abandonment', 'Отток на оформлении'), ('revenue_per_visitor', 'Выручка на посетителя'), ('ltv', 'LTV'), ('retention', 'Удержание'), ('churn', 'Отток'), ('romi', 'ROMI'), ('product_margin', 'Маржа товара')], db_index=True, max_length=50, verbose_name='Тип метрики'),
        ),
        migrations.AlterField(
            model_name='aggregatedstat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='aggregatedstat',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='aggregatedstat',
            name='value_prev',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Пред. значение'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='event_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Просмотр страницы'), ('scroll_depth', 'Глубина скролла'), ('click', 'Клик'), ('add_to_cart', 'Добавление в корзину'), ('remove_from_cart', 'Удаление из корзины'), ('checkout_start', 'Начало оформления'), ('checkout_step', 'Шаг оформления'), ('purchase', 'Покупка'), ('web_vital', 'Web Vitals'), ('custom', 'Другое')], db_index=True, max_length=50, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='page_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.trackingsession', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='url',
            field=models.URLField(max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='browser',
            field=models.CharField(blank=True, max_length=50, verbose_name='Браузер'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Компьютер'), ('mobile', 'Мобильный'), ('tablet', 'Планшет'), ('unknown', 'Неизвестно')], default='unknown', max_length=20, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='ip_hash',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Хеш IP'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='landing_page',
            field=models.URLField(blank=True, max_length=500, verbose_name='Целевая страница'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='os',
            field=models.CharField(blank=True, max_length=50, verbose_name='ОС'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='referer',
            field=models.URLField(blank=True, max_length=500, verbose_name='Referer'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='session_key',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Ключ сессии'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=200, verbose_name='UTM Campaign'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='utm_content',
            field=models.CharField(blank=True, max_length=200, verbose_name='UTM Content'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM Medium'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='UTM Source'),
        ),
        migrations.AlterField(
            model_name='trackingsession',
            name='utm_term',
            field=models.CharField(blank=True, max_length=200, verbose_name='UTM Term'),
        ),
    ]
