# Generated by Django 5.2.10 on 2026-03-04 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0006_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outgoing', 'Исходящее'), ('incoming', 'Входящее')], default='outgoing', max_length=10, verbose_name='Направление')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('failed', 'Ошибка отправки')], default='pending', max_length=10, verbose_name='Статус')),
                ('telegram_message_id', models.IntegerField(blank=True, null=True, verbose_name='ID сообщения в Telegram')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='store.telegramuser', verbose_name='Telegram пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telegram_user', '-created_at'], name='telegram_ap_telegra_4fb98d_idx'), models.Index(fields=['direction', 'status'], name='telegram_ap_directi_560b4c_idx')],
            },
        ),
    ]
