# Generated by Django 5.2.10 on 2026-03-04 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_telegramuser'),
        ('telegram_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID сессии')),
                ('status', models.CharField(choices=[('opened', 'Открыто'), ('closed', 'Закрыто'), ('active', 'Активно')], default='opened', max_length=10, verbose_name='Статус')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], default='unknown', max_length=20, verbose_name='Платформа')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Время открытия')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('start_param', models.CharField(blank=True, max_length=200, verbose_name='Параметр запуска (start_param)')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='store.telegramuser', verbose_name='Telegram пользователь')),
            ],
            options={
                'verbose_name': 'Журнал посещений',
                'verbose_name_plural': 'Журналы посещений',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['telegram_user', '-opened_at'], name='telegram_ap_telegra_e6b9b4_idx'), models.Index(fields=['status', 'opened_at'], name='telegram_ap_status_25e731_idx'), models.Index(fields=['session_id'], name='telegram_ap_session_dfb760_idx')],
            },
        ),
    ]
