"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env.local first (for local dev), then .env
BASE_DIR = Path(__file__).resolve().parent.parent
local_env = BASE_DIR / '.env.local'
if local_env.exists():
    load_dotenv(local_env, override=True)
else:
    load_dotenv(override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-n8nggd!y%!q*io0@@7jnuc)3qeq@1210doisz+ffmv0uijlx7=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'tlpn.shop,www.tlpn.shop,localhost').split(',')

# Telegram settings
TELEGRAM_BOT_TOKEN = '8731264310:AAFHZh55HF5nGdNL8oprvitY8W8srs3II_s'
TELEGRAM_WEBAPP_URL = 'tlpn.shop'
TELEGRAM_ADMIN_ID = '645419280'  # ID админа для уведомлений

# Order settings
MIN_ORDER_AMOUNT = 150  # Минимальная сумма заказа (руб)
FREE_DELIVERY_AMOUNT = 5000  # Бесплатная доставка от суммы (руб)

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    # Third party
    'imagekit',
    'rest_framework',
    'django_filters',
    # Local apps
    'store',
    'orders',
    'telegram_app',
    'analytics',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Analytics
    'analytics.middleware.AnalyticsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': "/opt/db/db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.getenv('STATIC_ROOT', str(BASE_DIR / 'staticfiles'))
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (product images)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('MEDIA_ROOT', str(BASE_DIR / 'media'))

# Ensure uploaded files/directories are web-readable in production.
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# Analytics Settings
# ============================================================================
ANALYTICS_SESSION_TIMEOUT = 30 * 60  # 30 минут
ANALYTICS_IP_SALT = SECRET_KEY  # Используем SECRET_KEY для хеширования IP

# Для продакшена - смените на уникальный salt
# ANALYTICS_IP_SALT = 'your-unique-salt-change-me'

# ============================================================================
# Local Settings (не хранить в git!)
# ============================================================================
# Этот файл используется для локальных переопределений настроек
# Создайте config/local_settings.py с нужными параметрами
try:
    from .local_settings import *
except ImportError:
    pass

# ============================================================================
# Caching Headers для статики (PageSpeed optimization)
# ============================================================================
# Добавляем заголовки кэширования для статических файлов
if not DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# ============================================================================
# Sitemap Settings
# ============================================================================
# Домен сайта для генерации sitemap.xml
SITEMAP_DOMAIN = 'tlpn.shop'
SITEMAP_PROTOCOL = 'https'
