from django.http import HttpResponse
from django.conf import settings


def robots(request):
    """
    Динамическая генерация robots.txt
    Позволяет управлять содержимым через настройки Django
    """
    # Получаем домен из настроек или используем значение по умолчанию
    domain = getattr(settings, 'SITEMAP_DOMAIN', 'tlpn.shop')
    protocol = getattr(settings, 'SITEMAP_PROTOCOL', 'https')
    
    lines = [
        '# robots.txt для Tulipa Shop (tlpn.shop)',
        '# Интернет-магазин тюльпанов',
        f'# Sitemap: {protocol}://{domain}/sitemap.xml',
        '',
        '# =============================================================================',
        '# Для всех поисковых роботов',
        '# =============================================================================',
        'User-agent: *',
        '',
        '# Разрешить индексацию публичных страниц',
        'Allow: /',
        'Allow: /item/',
        'Allow: /?category=',
        '',
        '# Запретить индексацию служебных разделов',
        'Disallow: /admin/',
        'Disallow: /bag/',
        'Disallow: /cart/',
        'Disallow: /checkout/',
        'Disallow: /profile/',
        'Disallow: /order-success/',
        'Disallow: /cart-sync/',
        'Disallow: /favorites/',
        'Disallow: /api/',
        'Disallow: /telegram/',
        'Disallow: /analytics/',
        '',
        '# Запретить URL с параметрами (фильтры, сортировка, utm-метки)',
        'Disallow: /*?*',
        'Disallow: /*&*',
        'Disallow: /*utm_*',
        'Disallow: /*filter=',
        'Disallow: /*sort=',
        'Disallow: /*page=',
        '',
        '# Разрешить CSS и JS для корректного рендеринга',
        'Allow: /static/css/',
        'Allow: /static/js/',
        'Allow: /static/fonts/',
        '',
        '# Разрешить изображения товаров для Google Images и Яндекс.Картинок',
        'Allow: /media/products/',
        '',
        '# =============================================================================',
        '# Для Яндекс (дополнительные настройки)',
        '# =============================================================================',
        'User-agent: Yandex',
        '',
        '# Разрешить индексацию публичных страниц',
        'Allow: /',
        'Allow: /item/',
        'Allow: /?category=',
        '',
        '# Запретить индексацию служебных разделов',
        'Disallow: /admin/',
        'Disallow: /bag/',
        'Disallow: /cart/',
        'Disallow: /checkout/',
        'Disallow: /profile/',
        'Disallow: /order-success/',
        'Disallow: /cart-sync/',
        'Disallow: /favorites/',
        'Disallow: /api/',
        'Disallow: /telegram/',
        'Disallow: /analytics/',
        '',
        '# Запретить URL с параметрами',
        'Disallow: /*?*',
        'Disallow: /*&*',
        'Disallow: /*utm_*',
        'Disallow: /*filter=',
        'Disallow: /*sort=',
        'Disallow: /*page=',
        '',
        '# Разрешить ресурсы для рендеринга',
        'Allow: /static/css/',
        'Allow: /static/js/',
        'Allow: /static/fonts/',
        'Allow: /media/products/',
        '',
        '# Главный хост для Яндекса',
        f'Host: {protocol}://{domain}/',
        '',
        '# =============================================================================',
        '# Sitemap',
        '# =============================================================================',
        f'Sitemap: {protocol}://{domain}/sitemap.xml',
        '',
    ]
    
    return HttpResponse('\n'.join(lines), content_type='text/plain; charset=utf-8')
