# Generated by Django 5.2.10 on 2026-02-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preferred_contact_method',
            field=models.CharField(default='telegram', max_length=20, verbose_name='Предпочтительный способ связи'),
        ),
    ]
