# Generated by Django 5.2.10 on 2026-02-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_preferred_contact_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram User ID'),
        ),
    ]
