# Generated by Django 5.2.10 on 2026-02-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_telegram_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Телефон'),
        ),
    ]
